apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: my-webserver
      labels:
        app: webserver
    spec:
      imagePullSecrets:          #docker hub 관련 정보 추가
      - name: dockerhub-secret #docker hub 관련 정보 추가
      containers:
      - name: my-webserver
      # 이미지는 본인 이미지로 변경 필요
        image: jaehyung725/echo-hostname:9b99e19a9c5670f8a51383e046292531c809e997
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
